services:
  - type: web
    name: aigentchat-dspy
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && mkdir -p logs templates"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.17.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
    autoDeploy: false
