services:
  - type: web
    name: aigentchat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
    startCommand: python api.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
