
services:
  - type: web
    name: aigentchat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      mkdir -p logs
      mkdir -p templates
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT api:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
