services:
  - type: web
    name: aigentchat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
