services:
  - type: web
    name: aigentchat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: python api.py
    envVars:
      - key: OPENAI_API_KEY='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'
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
