services:
  - type: web
    name: ai-agent-monitor
    runtime: python
    buildCommand: |
      echo "Starting build process..."
      pip install -r requirements.txt
      echo "Frontend build starting..."
      cd frontend
      npm install
      npm run build
      cd ..
      echo "Running startup checks..."
      python start.py
    startCommand: gunicorn -k eventlet -w 1 --bind 0.0.0.0:$PORT api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"
    autoDeploy: false
